name: 'Build widget'
inputs:
  productToken:
    description: 'AmoDEV product token'
    required: true
    default: ''
  productVersion:
    description: 'AmoDEV product version'
    required: true
    default: ''
runs:
  using: node12
  main: 'dist/index.js'
